### ISSUE TITLE
Wildcard inputs are not displayed

### ISSUE THREAD

**Issue by SirVeggie** [vivax3794/ComfyUI-Sub-Nodes#26]
Wildcard (*) input types do not appear in the subgraph node. Inputs that are connected to any wildcard nodes also do not appear.

**Comment by SirVeggie** [comment]
![image](https://github.com/user-attachments/assets/24ed9f73-7725-4f8b-913c-8db7eb67e143)
![image](https://github.com/user-attachments/assets/715ad7aa-e645-4b55-bb04-86dad3432bb0)

**Comment by SirVeggie** [comment]
nevermind, it appears after swapping the workflow setting back and forth (usually I just reload the page to get the changes)

**Comment by vivax3794** [comment]
Thats a unfortunate UX issue, loading the data for the subgraph is really messy tbh.
Because when loading after refreshing the page/loading from file we dont want to recreate the inputs as that would remove widgets that are converted to inputs, so when loading the page we actually dont reload inputs and just leave them as is. (we only reload outputs and widgets)

**Comment by vivax3794** [comment]
it might be possible to do some smart recreation of the inputs, but that seems fragile and comes with its own mountain of edge cases

**Comment by SirVeggie** [comment]
It's fine as it is currently, or at least the other issues are more important.
